In [1]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv(r"C:\Users\ADC\Desktop\ICU_MLOps_Project\data\raw\ICU.csv")

print("Dataset Loaded Successfully")
print(df.shape)

df.head()

Dataset Loaded Successfully
(200, 10)

,Unnamed: 0,ID,Survive,Age,AgeGroup,Sex,Infection,SysBP,Pulse,Emergency
0,1,4,0,87,3,1,1,80,96,1
1,2,8,1,27,1,1,1,142,88,1
2,3,12,1,59,2,0,0,112,80,1
3,4,14,1,77,3,0,0,100,70,0
4,5,27,0,76,3,1,1,128,90,1

In [3]:
df = df.drop(columns=["Unnamed: 0", "ID"])

print(df.shape)

df.head()

(200, 8)

   Survive  Age  AgeGroup  Sex  Infection  SysBP  Pulse  Emergency
0        0   87         3    1          1     80     96          1
1        1   27         1    1          1    142     88          1
2        1   59         2    0          0    112     80          1
3        1   77         3    0          0    100     70          0
4        0   76         3    1          1    128     90          1

In [4]:
X = df.drop("Survive", axis=1)

y = df["Survive"]

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (200, 7)
Target Shape : (200,)

In [5]:
print("Feature Columns:")
print(X.columns.tolist())

print("\nTarget Column:")
print(y.name)

Feature Columns:
['Age', 'AgeGroup', 'Sex', 'Infection', 'SysBP', 'Pulse', 'Emergency']

Target Column:
Survive

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [7]:
print("="*50)
print("Training Data")
print("="*50)

print(X_train.shape)
print(y_train.shape)

print("\n")

print("="*50)
print("Testing Data")
print("="*50)

print(X_test.shape)
print(y_test.shape)

==================================================
Training Data
==================================================
(160, 7)
(160,)


==================================================
Testing Data
==================================================
(40, 7)
(40,)

In [8]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [10]:
X_train_scaled = pd.DataFrame(
X_train_scaled,
columns=X.columns,
index=X_train.index
)

X_test_scaled = pd.DataFrame(
X_test_scaled,
columns=X.columns,
index=X_test.index
)

In [11]:
X_train_scaled.head()

          Age  AgeGroup       Sex  Infection     SysBP     Pulse  Emergency
56  -0.843763 -1.315695 -0.764303   1.193416  0.220394 -1.566410   0.635223
154  0.594012  1.205397 -0.764303   1.193416 -1.787239  1.639968   0.635223
174 -0.397557 -0.055149 -0.764303   1.193416  0.738493 -0.019804   0.635223
157 -0.893342 -1.315695 -0.764303   1.193416  0.868018  1.904023   0.635223
122  1.486424  1.205397  1.308382  -0.837931 -0.751041 -2.019076  -1.574249

In [12]:
joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

print("Scaler Saved Successfully")

Scaler Saved Successfully

In [13]:
train_processed = X_train_scaled.copy()

train_processed["Survive"] = y_train.values

train_processed.to_csv(
    "../data/processed/train_processed.csv",
    index=False
)

In [14]:
test_processed = X_test_scaled.copy()

test_processed["Survive"] = y_test.values

test_processed.to_csv(
    "../data/processed/test_processed.csv",
    index=False
)

In [15]:
print("="*60)
print("PREPROCESSING COMPLETED SUCCESSFULLY")
print("="*60)

print("Original Dataset :", df.shape)

print("Training Data :", X_train_scaled.shape)

print("Testing Data :", X_test_scaled.shape)

print("Scaler Saved : Yes")

print("Processed Data Saved : Yes")

============================================================
PREPROCESSING COMPLETED SUCCESSFULLY
============================================================
Original Dataset : (200, 8)
Training Data : (160, 7)
Testing Data : (40, 7)
Scaler Saved : Yes
Processed Data Saved : Yes